image: gitpod/workspace-python

ports:
  - port: 5000
    description: USMB - Website
  - port: 5001
    description: USMB - API

tasks:
  - init: >
      pip install -r requirements.txt &&
      pip install --upgrade pip &&
      sudo apt-get update && 
      sudo apt-get install mariadb-server -y && 
      sudo /etc/init.d/mysql start

vscode:
  extensions:
    - ms-python.python
